Repository oh930428/purplestone-storybook, pull requests merged in 2022-05, with the labels that each got.

#1 [feat] add storybook
  .storybook/main.js
  .storybook/preview.js
  README.md
  package.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/assets/code-brackets.svg
  src/assets/colors.svg
  src/assets/comments.svg
  src/assets/direction.svg
  src/assets/flow.svg
  src/assets/plugin.svg
  src/assets/repo.svg
  src/assets/stackalt.svg
  src/components/Button/Button.tsx
  src/components/Button/button.css
  src/components/Header/Header.tsx
  src/components/Header/header.css
  src/components/page/Page.tsx
  src/components/page/page.css
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/stories/Button.stories.tsx
  src/stories/Header.stories.tsx
  src/stories/Page.stories.tsx
  yarn.lock
Labels: 📦 - [ package ], 🔥 - [ remove ], 🚚 - [ rename ]

#2 [feat] colors 디자인 시스템 추가
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/Colors/ColorCard.tsx
  src/components/Colors/Colors.tsx
  src/stories/Colors.stories.tsx
  yarn.lock
Labels: 👷 - [ chore ], ✨ - [ feat ], 🎨 - [ style ]

#4 [feat] MakeMyCardSmall 스토리북 추가
  package-lock.json
  src/assets/Icons/ice.png
  src/assets/Icons/morning.png
  src/assets/images/bg-card-small.png
  src/assets/images/bg-card.png
  src/assets/images/bg-digram-small.png
  src/assets/images/bg-digram.png
  src/assets/images/coffee.png
  src/components/Card/MakeMyCard/MakeMyCard.tsx
  src/components/Card/MakeMyCardSmall/Icon.tsx
  src/components/Card/MakeMyCardSmall/MakeMyCardSmall.tsx
  src/components/Font/Font.tsx
  src/stories/Font.stories.tsx
  src/stories/MakeMyCard.stories.tsx
  src/stories/MakeMyCardSmall.stories.tsx
  src/styles/font.ts
  src/types/makeMyCard.type.ts
  yarn.lock
Labels: ✨ - [ feat ]

#5 [feat]MakeMyCardSmall 스토리북 추가
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  src/assets/Icons/ice.png
  src/assets/Icons/morning.png
  src/assets/images/bg-card-small.png
  src/assets/images/bg-digram-small.png
  src/assets/images/ice.png
  src/assets/images/morning.png
  src/components/Card/MakeMyCardSmall/Icon.tsx
  src/components/Card/MakeMyCardSmall/MakeMyCardSmall.tsx
  src/components/Colors/ColorCard.tsx
  src/components/Colors/Colors.tsx
  src/stories/Colors.stories.tsx
  src/stories/MakeMyCard.stories.tsx
  src/stories/MakeMyCardSmall.stories.tsx
  yarn.lock
Labels: ✨ - [ feat ]

#6 [feat] 세션 헤더 타이틀 컴포넌트 추가
  .storybook/preview-head.html
  src/components/HeaderSection/HeaderSection.tsx
  src/stories/HeaderSection.stories.tsx
Labels: 🐛 - [ fix ], ✨ - [ feat ]

#10 [feat]profileCard UI 추가 및 스토리북, 아이콘 추가
  .storybook/preview-head.html
  src/assets/Icons/facebook.png
  src/assets/Icons/google.png
  src/assets/Icons/instagram.png
  src/assets/Icons/profile.png
  src/assets/images/bg-profile-card.png
  src/components/Button/Button.tsx
  src/components/Card/ProfileCard/ProfileCard.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/header.css
  src/components/Icon/IconSocial.tsx
  src/components/Navigation/Navigation.tsx
  src/components/page/Page.tsx
  src/components/page/page.css
  src/stories/Button.stories.tsx
  src/stories/Footer.stories.tsx
  src/stories/Header.stories.tsx
  src/stories/Icon.stories.tsx
  src/stories/Navigation.stories.tsx
  src/stories/Page.stories.tsx
  src/stories/ProfileCard.stories.tsx
Labels: ✨ - [ feat ]

#11 [feat] processCard UI 개발 및 profileCard UI 개발
  src/assets/Icons/bluecuracaoSyrup.png
  src/assets/Icons/brazilSantos.png
  src/assets/Icons/caramelSyrup.png
  src/assets/Icons/coffeebean.png
  src/assets/Icons/colombiaDecaffein.png
  src/assets/Icons/colombiaOrganic.png
  src/assets/Icons/colombiaSupremo.png
  src/assets/Icons/disposableCup.png
  src/assets/Icons/ediya.png
  src/assets/Icons/evening.png
  src/assets/Icons/guatemalaSHB.png
  src/assets/Icons/hazelnutSyrup.png
  src/assets/Icons/hot.png
  src/assets/Icons/ice.png
  src/assets/Icons/lessIce.png
  src/assets/Icons/lunch.png
  src/assets/Icons/manyIce.png
  src/assets/Icons/mexicoAlturaOrganic.png
  src/assets/Icons/morning.png
  src/assets/Icons/mugCup.png
  src/assets/Icons/profile.png
  src/assets/Icons/reuseableCup.png
  src/assets/Icons/starbucks.png
  src/assets/Icons/twosome.png
  src/assets/Icons/vainillaSyrup.png
  src/assets/images/bg-profile-card.png
  src/components/Card/ProcessCard/ProcessCard.tsx
  src/components/Card/ProfileCard/ProfileCard.tsx
  src/stories/ProcessCard.stories.tsx
  src/stories/ProfileCard.stories.tsx
Labels: ✨ - [ feat ]

#12 [feat] navigation 컴포넌트 디자인 수정, 커피 선택 옵션 스토리 추가
  src/assets/Icons/beans.png
  src/assets/Icons/bluecuracaoSyrup-small.png
  src/assets/Icons/brand.png
  src/assets/Icons/coffee.png
  src/assets/Icons/ice-big.png
  src/assets/Icons/morning-big.png
  src/assets/Icons/syrup.png
  src/assets/images/bg-circle-active.png
  src/assets/images/bg-circle.png
  src/components/CoffeeOption/CoffeeOption.tsx
  src/components/Navigation/Navigation.tsx
  src/stories/CoffeeOption.stories.tsx
Labels: ✨ - [ feat ]

#13 [set] 스토리북 카테고리 수정
  src/assets/code-brackets.svg
  src/assets/colors.svg
  src/assets/comments.svg
  src/assets/direction.svg
  src/assets/flow.svg
  src/assets/plugin.svg
  src/assets/repo.svg
  src/assets/stackalt.svg
  src/components/Card/MakeMyCardSmall/Icon.tsx
  src/components/Header/Header.tsx
  src/stories/Colors.stories.tsx
  src/stories/Font.stories.tsx
  src/stories/Header.stories.tsx
  src/stories/MakeMyCard.stories.tsx
  src/stories/MakeMyCardSmall.stories.tsx
  src/stories/ProcessCard.stories.tsx
  src/stories/ProfileCard.stories.tsx
Labels: 🔨 - [ set ], 🔥 - [ remove ], 🚚 - [ rename ]

#14 [feat] Button: theme 스토리 추가 및 css 수정, Typography 스토리 추가
  src/components/Button/Button.tsx
  src/components/Button/button.css
  src/components/Font/Font.tsx
  src/components/Typography/Typography.tsx
  src/stories/Button.stories.tsx
  src/stories/Font.stories.tsx
  src/stories/Typography.stories.tsx
Labels: ✨ - [ feat ]

#15 [feat] Colors.stories.mdx 파일로 변경
  .storybook/main.js
  package.json
  src/assets/Icons/beans.png
  src/assets/Icons/bluecuracaoSyrup-small.png
  src/assets/Icons/brand.png
  src/assets/Icons/coffee.png
  src/assets/Icons/ice-big.png
  src/assets/Icons/morning-big.png
  src/assets/Icons/syrup.png
  src/assets/images/bg-circle-active.png
  src/assets/images/bg-circle.png
  src/components/Button/Button.tsx
  src/components/Button/button.css
  src/components/CoffeeOption/CoffeeOption.tsx
  src/components/Colors/Colors.tsx
  src/components/Font/Font.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Typography/Typography.tsx
  src/stories/Button.stories.tsx
  src/stories/CoffeeOption.stories.tsx
  src/stories/Colors.stories.mdx
  src/stories/Colors.stories.tsx
  src/stories/Typography.stories.tsx
  yarn.lock
Labels: 🐛 - [ fix ], 🔨 - [ set ], 📦 - [ package ], ✨ - [ feat ]

#16 [feat]Colors.stories.mdx 파일로 변경
  .storybook/main.js
  package.json
  src/components/Colors/Colors.tsx
  src/components/Navigation/Navigation.tsx
  src/stories/Colors.stories.mdx
  src/stories/Colors.stories.tsx
  src/stories/Typography.stories.tsx
  yarn.lock
Labels: 🐛 - [ fix ], 🔨 - [ set ], 📦 - [ package ], ✨ - [ feat ]

#17 [set] 마크업 수정 및 조건부 클래스 추가 및 커피 옵션 이미지 추가
  src/assets/Icons/coffee-pack.png
  src/assets/Icons/coffee2.png
  src/assets/Icons/cup-black.png
  src/assets/Icons/cup-blue.png
  src/assets/Icons/cup-brown.png
  src/assets/Icons/cup-glass.png
  src/assets/Icons/cup-green.png
  src/assets/Icons/cup-yellow.png
  src/assets/Icons/disposableCup.png
  src/assets/Icons/mug-cup.png
  src/assets/Icons/mugCup.png
  src/assets/Icons/reuseableCup-small.png
  src/assets/Icons/syrup.png
  src/components/CoffeeOption/CoffeeOption.tsx
  src/stories/CoffeeOption.stories.tsx
Labels: 🔨 - [ set ]

#19 🔨[set] : 커피 종류 타입 processCard 추가
  src/assets/Icons/coffeetypes/americano.png
  src/assets/Icons/coffeetypes/caffelatte.png
  src/assets/Icons/coffeetypes/caffemoca.png
  src/assets/Icons/coffeetypes/cappuccino.png
  src/assets/Icons/coffeetypes/espresso.png
  src/assets/Icons/coffeetypes/macchiato.png
  src/stories/ProcessCard.stories.tsx
Labels: 🔨 - [ set ], 💄 - [ design ]

#20 [remove] Images 폴더 삭제
  src/assets/Images/profile.png
Labels: 🔥 - [ remove ]

#21 💄[ design ] profile 이미지 출가
  src/assets/Images/profile.png
Labels: 💄 - [ design ]

#22 ✨ [ feat ] Chart UI 추가 및 스토리북 추가
  package-lock.json
  package.json
  src/components/Chart/Chart.tsx
  src/components/Chart/Doghnut.tsx
  src/stories/Chart.stories.tsx
  yarn.lock
Labels: 📦 - [ package ], ✨ - [ feat ]

#23 ✨ [ feat ] Chart UI 추가 및 스토리북 추가
  package-lock.json
  package.json
  src/components/Chart/Chart.tsx
  src/components/Chart/Doghnut.tsx
  src/stories/Chart.stories.tsx
  yarn.lock
Labels: 📦 - [ package ], ✨ - [ feat ]

#24 [set] 카드 컴포넌트들 이미지 업로드 및 사이즈 수정, ProcessCard 컴포넌트 css 수정, MakeMyCard Input auto width 기능 추가
  src/assets/Icons/beans/colombiaSupremo.png
  src/assets/Icons/beans/ethiopiaYirgacheffee.png
  src/assets/Icons/beans/guatemalaAntiguaSHB.png
  src/assets/Icons/beans/jamaicaBlueMountain.png
  src/assets/Icons/beans/kenyaAA.png
  src/assets/Icons/beans/tanzaniaAA.png
  src/assets/Icons/bottles/cup-black.png
  src/assets/Icons/bottles/cup-brown.png
  src/assets/Icons/bottles/cup-disposable.png
  src/assets/Icons/bottles/cup-glass.png
  src/assets/Icons/bottles/cup-mug.png
  src/assets/Icons/bottles/cup-reuseable.png
  src/assets/Icons/bottles/cup-takeout-hot.png
  src/assets/Icons/bottles/cup-tea.png
  src/assets/Icons/bottles/cup-tumbler.png
  src/assets/Icons/bottles/cup-yellow.png
  src/assets/Icons/brands/coffeebean.png
  src/assets/Icons/brands/ediya.png
  src/assets/Icons/brands/hollys.png
  src/assets/Icons/brands/starbucks.png
  src/assets/Icons/brands/twosome.png
  src/assets/Icons/coffeetypes/americano.png
  src/assets/Icons/coffeetypes/americano2.png
  src/assets/Icons/coffeetypes/caffelatte.png
  src/assets/Icons/coffeetypes/caffelatte2.png
  src/assets/Icons/coffeetypes/caffemoca.png
  src/assets/Icons/coffeetypes/caffemocha.png
  src/assets/Icons/coffeetypes/caffemocha2.png
  src/assets/Icons/coffeetypes/cappuccino.png
  src/assets/Icons/coffeetypes/cappuccino2.png
  src/assets/Icons/coffeetypes/espresso.png
  src/assets/Icons/coffeetypes/espresso2.png
  src/assets/Icons/coffeetypes/macchiato.png
  src/assets/Icons/coffeetypes/macchiato2.png
  src/assets/Icons/temperature/hot.png
  src/assets/Icons/temperature/ice.png
  src/components/Card/MakeMyCard/MakeMyCard.tsx
  src/components/Card/ProcessCard/ProcessCard.tsx
  src/components/CoffeeOption/CoffeeOption.tsx
  src/stories/MakeMyCard.stories.tsx
  src/stories/MakeMyCardSmall.stories.tsx
  src/stories/ProcessCard.stories.tsx
  src/types/makeMyCard.type.ts
Labels: 🔨 - [ set ], ✨ - [ feat ], 🔥 - [ remove ], 💄 - [ design ]

#25 ♻️ [ refactor ]각 UI 컴포넌트 interface -> types폴더 안에 파일로 변경 및 styles 폴더에 fonts, colors로 호출 변경
  src/components/Button/Button.tsx
  src/components/Card/MakeMyCard/MakeMyCard.tsx
  src/components/Card/MakeMyCardSmall/Icon.tsx
  src/components/Card/MakeMyCardSmall/MakeMyCardSmall.tsx
  src/components/Card/ProcessCard/ProcessCard.tsx
  src/components/Card/ProfileCard/ProfileCard.tsx
  src/components/Chart/Chart.tsx
  src/components/Chart/Doghnut.tsx
  src/components/CoffeeOption/CoffeeOption.tsx
  src/components/Colors/ColorCard.tsx
  src/components/Colors/Colors.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Icon/IconSocial.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Typography/Typography.tsx
  src/stories/Button.stories.tsx
  src/stories/Chart.stories.tsx
  src/stories/CoffeeOption.stories.tsx
  src/stories/Colors.stories.mdx
  src/stories/Footer.stories.tsx
  src/stories/Header.stories.tsx
  src/stories/Icon.stories.tsx
  src/stories/MakeMyCard.stories.tsx
  src/stories/MakeMyCardSmall.stories.tsx
  src/stories/Navigation.stories.tsx
  src/stories/ProcessCard.stories.tsx
  src/stories/ProfileCard.stories.tsx
  src/styles/colors.ts
  src/styles/index.ts
  src/types/button.type.ts
  src/types/chart.type.ts
  src/types/coffeeOption.type.ts
  src/types/colors.type.ts
  src/types/header.type.ts
  src/types/iconSocial.type.ts
  src/types/makeMyCard.type.ts
  src/types/makeMyCardSmall.type.ts
  src/types/processCard.type.ts
  src/types/profileCard.type.ts
Labels: ♻️ - [ refactor ], 🔨 - [ set ]

#26 🔨 [set] MakeMyCard.type -> makeMyCard.type 으로 변경
  src/components/Card/MakeMyCard/MakeMyCard.tsx
  src/stories/MakeMyCard.stories.tsx
Labels: 🔨 - [ set ]

#27 🔨 [set] Chart 타입 styles, options 추가
  src/components/Chart/Chart.tsx
  src/components/Chart/Doghnut.tsx
  src/stories/Chart.stories.tsx
  src/types/chart.type.ts
Labels: 🔨 - [ set ]

#28 ♻️ [ refactor ] MakeMyCard 에서 input auto width 리팩토링
  src/components/Card/MakeMyCard/MakeMyCard.tsx
Labels: ♻️ - [ refactor ]
